FROM ubuntu

RUN apt-get update

RUN apt-get install nodejs -y npm

RUN apt-get install -y npm

RUN npm install -g npm

RUN npm install -g mountebank

RUN apt-get install -y curl

EXPOSE 5000

CMD mb 





